# Generated by Django 4.2 on 2023-06-26 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='updated',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 13, 27, 14, 171656)),
        ),
    ]
