# Generated by Django 4.2 on 2023-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_chatthread_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default='2023-06-26T17:48:53.852133'),
        ),
    ]
