# Generated by Django 4.2 on 2023-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olxuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
