# Generated by Django 4.2 on 2023-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLX', '0007_alter_accessoryad_posted_user_alter_ad_images_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsad',
            name='km_driven',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
