# Generated by Django 4.2 on 2023-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLX', '0009_carsad_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooterad',
            name='brand',
            field=models.CharField(choices=[('Bajaj', 'Bajaj'), ('Hero', 'Hero'), ('Honda', 'Honda'), ('Mahindra', 'Mahindra'), ('Suzuki', 'Suzuki'), ('TVS', 'TVS')], default=''),
            preserve_default=False,
        ),
    ]
