# Generated by Django 4.2 on 2023-05-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OLX', '0010_scooterad_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessoryad',
            old_name='type',
            new_name='accessory_type',
        ),
    ]
